# Site settings
title: Andrey Kitsen
name: Andrey Kitsen

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/akitsen
 - title: LinkedIn
   url: https://www.linkedin.com/in/andrey-kitsen/

#Any buzzword skills you want to include
skills:
 - Groovy
 - PowerShell
 - Java
 - SQL
 - REST

#Work experience is required
roles:
 - title: Senior Monitoring Engineer
   start: 2015
   end: Ongoing
   employer: LogicMonitor
   description: SaaS based IT Infrastructure Monitoring 
 - title: Linux & Storage System Admin
   start: 2013
   end: 2015
   employer: Westmont College
   description: Westmont College
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2013-2015
   subject: Computer Science & Machine Learning
   school: Westmont College
 - level: Bachelor of Science (B.Sc.)
   date: 2010-2013
   subject: Business Information Technology
   school: California State University Fresno
   
#List of interesting Github repo/projects to include - optional
github:
 - logicmonitor/monitoring-recipes
 - akitsen/Bathroom-Monitor-NodeMCU-ESP-8266
 - akitsen/Neopolitan
 - akitsen/Playing-With-JavaScript
 - akitsen/Network-Chat-Client
 - akitsen/LMFunWidget

